rhbase_firewall_allow_services:
  - samba
  - ftp
rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public
samba_netbios_name: FILES
samba_workgroup: AVALON
samba_load_printers: false
vsftpd_anonymous_enable: false
vsftpd_local_enable: true
vsftpd_local_root: /srv/shares/
rhbase_users:
  - name: benjamin
    comment: 'Benjamin Van Lierde'
    password: BenVlie
    groups:
      - wheel
      - it
      - public
  - name: anc
    comment: 'An Coppens'
    password: anc
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: alexanderd
    comment: 'Alexander De Coninck'
    password: alexanderd
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: benoitp
    comment: 'Benoit Pluquet'
    password: benoitp
    shell: /sbin/nologin
    groups:
      - public
      - sales
  - name: christophev
    comment: 'Christophe Van der Meersche'
    password: christophev
    groups:
      - public
      - it
  - name: elenaa
    comment: 'Elena Andreev'
    password: elenaa
    shell: /sbin/nologin
    groups:
      - public
      - management
  - name: evyt
    comment: 'Evy Tilleman'
    password: evyt
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: krisv
    comment: 'Kris Vanhaverbeke'
    password: krisv
    shell: /sbin/nologin
    groups:
      - public
      - management
  - name: leend
    comment: 'Leen De Meester'
    password: leend
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: nehirb
    comment: 'Nehir Basar'
    password: nehirb
    groups:
      - public
      - it
  - name: stefaanv
    comment: 'StefaanVernimmen'
    password: stefaanv
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: stevenh
    comment: 'Steven Hermans'
    password: stevenh
    shell: /sbin/nologin
    groups:
      - public
      - management
  - name: stevenv
    comment: 'Steven Van Daele'
    password: stevenv
    shell: /sbin/nologin
    groups:
      - public
      - technical
  - name: svena
    comment: 'Sven Aerens'
    password: svena
    shell: /sbin/nologin
    groups:
      - public
      - sales
samba_users:
  - name: alexanderd
    password: alexanderd
  - name: anc
    password: anc
  - name: benoitp
    password: benoitp
  - name: christophev
    password: christophev
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: krisv
    password: krisv
  - name: leend
    password: leend
  - name: nehirb
    password: nehirb
  - name: stefaanv
    password: stefaanv
  - name: stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: svena
    password: svena
  - name: benjamin
    password: benvlie

samba_shares:
  - name: public
    comment: 'Public share'
    group: public
    valid_users: +public
    write_list: +public
    guest_ok: no
  - name: management
    comment: 'Management share'
    group: management
    valid_users: +management
    write_list: +management
    guest_ok: no
  - name: technical
    comment: 'Technical share'
    group: technical
    valid_users: +technical, +public
    write_list: +technical
    guest_ok: no
  - name: sales
    comment: 'sales share'
    group: sales
    valid_users: +sales, +management
    write_list: +sales
    guest_ok: no
  - name: it
    comment: 'it share'
    group: it
    valid_users: +it, +management
    write_list: +it
    guest_ok: no
