# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
 - epel-release
rhbase_install_packages:
 - bash-completion
 - vim-enhanced
rhbase_firewall_allow_services:
 - http
 - https
